base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path("register/", views.register ,name="register"),
    path('car/<str:pk>/', views.car, name='car'),
    path('new-order/', views.new_order, name='new_order'),
    path('edit-order/<str:pk>', views.edit_car, name='edit_car'),
    path('chat/', views.new_order, name='new_order'),
    path('profile/', views.my_profile, name='my_profile'),
    path('user_profile/<str:pk>', views.user_profile, name='user_profile'),
    path('chat/<int:recipient_id>/', views.chat, name='chat'),
    path('my_chats/', views.view_chats, name='my_chats'),
    path('my_listings/', views.my_listings, name='my_listings'),
]

otomoto/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.exceptions import ValidationError


import pytz
import datetime


def validate_registration_year(year):
    if year < 1900 or year > 2024:
        raise ValidationError(
            'Wrong first registration year. Has to be between 1900 and 2024.'
        )

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True, null=True)
    birth_date = models.DateField(null=True, blank=True)
    contact_number = models.CharField(max_length=12, null=True, blank=True)
    
    def __str__(self):
        return self.user.username
       
    
class Car(models.Model):
    BRAND = (
        ('Abarth', 'Abarth'),
        ('Alfa Romeo', 'Alfa Romeo'),
        ('Aston Martin', 'Aston Martin'),
        ('Audi', 'Audi'),
        ('Bentley', 'Bentley'),
        ('BMW', 'BMW'),
        ('Chevrolet', 'Chevrolet'),
        ('Chrysler', 'Chrysler'),
        ('Citroen', 'Citroen'),
        ('Dacia', 'Dacia'),
        ('Dodge', 'Dodge'),
        ('Ferrari', 'Ferrari'),
        ('Fiat', 'Fiat'),
        ('Ford', 'Ford'),
        ('GMC', 'GMC'),
        ('Honda', 'Honda'),
        ('Hundai', 'Hundai'),
        ('Infiniti', 'Infiniti'),
        ('Jaguar', 'Jaguar'),
        ('Jeep', 'Jeep'),
        ('Kia', 'Kia'),
        ('Lamborghini', 'Lamborghini'),
        ('Land Rover', 'Land Rover'),
        ('Lexus', 'Lexus'),
        ('Lancia', 'Lancia'),
        ('Lotus', 'Lotus'),
        ('Maserati', 'Maserati'),
        ('Mazda', 'Mazda'),
        ('Mercedes-Benz', 'Mercedes-Benz'),
        ('Mitsubishi', 'Mitsubishi'),
        ('Nissan', 'Nissan'),
        ('Opel', 'Opel'),
        ('Peugeot', 'Peugeot'),
        ('Porsche', 'Porsche'),
        ('Renault', 'Renault'),
        ('Seat', 'Seat'),
        ('Skoda', 'Skoda'),
        ('Subaru', 'Subaru'),
        ('Suzuki', 'Suzuki'),
        ('Tesla', 'Tesla'),
        ('Toyota', 'Toyota'),
        ('Volvo', 'Volvo'),
        ('Volkswagen', 'Volkswagen'),
        ('Other', 'Other')
    )
    
    BODY_TYPE = (
        ('Compact', 'Compact'),
        ('Convertible', 'Convertible'),
        ('Coupe', 'Coupe'),
        ('SUV', 'SUV'),
        ('Station wagon', 'Station wagon'),
        ('Sedan', 'Sedan'),
        ('Van', 'Van'),
        ('Transporter', 'Transporter'),
        ('Other', 'Other'),
    )

    FUEL_TYPE = (
        ('Gasoline', 'Gasoline'),
        ('Diesel', 'Diesel'),
        ('LPG', 'LPG'),
        ('Electric', 'Electric'),
    )

    TRANSMISSION_TYPE = (
        ('Manual', 'Manual'),
        ('Automatic', 'Automatic')
    )

    user = models.ForeignKey(User, default=None ,on_delete=models.CASCADE)
    
    
    brand = models.CharField(max_length=100, choices=BRAND)
    model = models.CharField(max_length=45)
    
    
    body = models.CharField(max_length=255, null=False, blank=False, choices=BODY_TYPE)
    first_registration_year = models.IntegerField(null=False, blank=False, default=datetime.datetime.today().year, validators=[validate_registration_year])
    horse_power = models.IntegerField(null=False, blank=False, default=None)
    mileage = models.IntegerField(default=None ,null= False, blank=False)
    transmission = models.CharField(max_length=255, choices=TRANSMISSION_TYPE, default=None)
    fuel_type = models.CharField(max_length=255, null=False, blank=False, default='None', choices=FUEL_TYPE)
    price = models.DecimalField(null=False, blank=False, default='0', max_digits=8, decimal_places=0)
    max_price = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=0)
    contact_number = models.CharField(default=None,max_length=12)
    description = models.TextField(null=True, blank=True)
    country = models.CharField(max_length=2, choices=pytz.country_names.items(), default=None)
    city = models.CharField(max_length=255, null=False, blank=False, default=None)
    car_images = models.ImageField(default='default_car.jpg')

    def __str__(self):
        return str(self.id)
    
class CarImage(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='car_images/')
    
 
class Chat(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False)
    participants = models.ManyToManyField(User)
    
    
    def __str__(self):
        return self.title 
   
class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    chat = models.ForeignKey(Chat, default=None, on_delete= models.CASCADE)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f'{self.sender} to {self.recipient} - {self.timestamp}'
    

base/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import Car, CarImage, Profile


class RegisterForm(UserCreationForm):
    class Meta:
        model=User
        fields = ['username','email','password1','password2'] 

class CarImageForm(forms.ModelForm):
    class Meta:
        model = CarImage
        fields = ['image']

    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       self.fields['image'].widget.attrs.update({'class': 'image_form'})
        
CarImageFormSet = forms.inlineformset_factory(Car, CarImage, form=CarImageForm, extra=1)

class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['brand', 'model', 'body', 'first_registration_year', 'horse_power', 'mileage', 'transmission',
                  'fuel_type', 'price', 'contact_number', 'description', 'country', 'city']
        
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       self.fields['brand'].widget.attrs.update({'class': 'order_button'})
       self.fields['model'].widget.attrs.update({'class': 'order_button'})
       self.fields['body'].widget.attrs.update({'class': 'order_button'})
       self.fields['first_registration_year'].widget.attrs.update({'class': 'order_button'})
       self.fields['horse_power'].widget.attrs.update({'class': 'order_button'})
       self.fields['mileage'].widget.attrs.update({'class': 'order_button'})
       self.fields['transmission'].widget.attrs.update({'class': 'order_button'})
       self.fields['fuel_type'].widget.attrs.update({'class': 'order_button'})
       self.fields['price'].widget.attrs.update({'class': 'order_button'})
       self.fields['contact_number'].widget.attrs.update({'class': 'order_button'})
       self.fields['description'].widget.attrs.update({'class': 'order_button1'})
       self.fields['country'].widget.attrs.update({'class': 'order_button'})
       self.fields['city'].widget.attrs.update({'class': 'order_button'})

CarImageFormSet = forms.inlineformset_factory(Car, CarImage, form=CarImageForm, extra=10)

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = [ 'birth_date', 'contact_number','bio']
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'bio'}),
            'birth_date': forms.DateInput(attrs={'class': 'birth_date', 'placeholder':'2024-01-22'}),
            'contact_number': forms.DateInput(attrs={'class': 'contact_number'}),
        }
        

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Car, Profile, User, Message, Chat
from .filters import CarFilter
from .forms import RegisterForm, CarForm , CarImageFormSet, ProfileForm

def index(request):
    page = 'index'
    filter = CarFilter(request.GET, queryset=Car.objects.all())
    cars = filter.qs

    order_by_options = {
        '1': 'price',
        '2': '-price',
        '3': 'horse_power',
        '4': '-horse_power',
        '5': 'first_registration_year',
        '6': '-first_registration_year',
    }

    order_by_param = request.GET.get('order_by', '-first_registration_year')
    
    if 'auto' in filter.data:
        order_by_param += f'&auto={filter.data["auto"]}'
    
        if 'brand' in filter.data:
            order_by_param += f'&brand={filter.data["brand"]}'
        if 'model' in filter.data:
                order_by_param += f'&model={filter.data["model"]}'
        if 'body' in filter.data:
                order_by_param += f'&body={filter.data["body"]}'
        if 'first_registration_year' in filter.data:
                order_by_param += f'&first_registration_year={filter.data["first_registration_year"]}'
        if 'fuel_type' in filter.data:
                order_by_param += f'&fuel_type={filter.data["fuel_type"]}'
        if 'max_price' in filter.data:
                order_by_param += f'&max_price={filter.data["max_price"]}'

    order_by_param = order_by_param.lstrip('&')
            
    cars = cars.order_by(order_by_options.get(order_by_param, '-first_registration_year'))

    return render(request, 'index.html', context={'cars': cars, 'filter': filter, 'order_by': order_by_param, 'page':page})
    
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        User = authenticate(request, username=username, password=password)
                
        if User is not None:
            auth_login(request, User)
            messages.success(request, f'Welcome back {username}')
            return redirect('index')
        else:
            messages.error(request,'Wrong password or username! Try again!')
                
    return render(request, 'login.html')

@login_required
def logout_user(request):
    logout(request)
    return redirect('index')

def register(request):
    form = RegisterForm()
  
    if request.method == 'POST':
        form = RegisterForm(request.POST) 
        if form.is_valid():
            user = form.save()
            user.save()
            Profile.objects.create(user=user)
            messages.success(request, f'You have singed up successfully. Welcome {user.username}!')
            auth_login(request, user)
            return redirect('index')
        else:
            messages.error(request, 'Something went wrong! Try again!')
            return render(request, 'register.html', {'form': form})
        
    return render(request, 'register.html', context={'form':form})


def car(request, pk):
    car = Car.objects.get(id=pk)
    return render(request, 'car.html', {'car': car})

@login_required
def new_order(request):
    if request.method == 'POST':
        form = CarForm(request.POST)
        formset = CarImageFormSet(request.POST, request.FILES, instance=Car())

        if form.is_valid() and formset.is_valid():
            car = form.save(commit=False)
            car.user = request.user
            car.save()
            formset.instance = car
            formset.save()
            return redirect('car', pk=car.pk)
    else:
        form = CarForm()
        formset = CarImageFormSet(instance=Car())

    return render(request, 'new_order.html', {'form': form, 'formset': formset})

@login_required
def edit_car(request, pk):
    car = Car.objects.get(id=pk)
    form = CarForm(instance=car)
    formset = CarImageFormSet(instance=car)
    
    if request.method == 'POST':
        form = CarForm(request.POST, instance=car)
        formset = CarImageFormSet(request.POST, request.FILES, instance=car)
        
        if form.is_valid() and formset.is_valid():
            car = form.save(commit=False)
            car.user = request.user
            car.save()
            formset.save()
            return redirect('car', pk=car.pk)
    
    return render(request, 'new_order.html', context={'form': form, 'formset': formset})

@login_required
def my_profile(request):
    user = request.user
    form = ProfileForm(instance=user.profile)
    
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=user.profile)
        if form.is_valid():
            form.save() 
            messages.success(request, 'Profile updated!')
            return redirect('my_profile')

    return render(request, 'my_profile.html', context={'user':user, 'form':form})

def user_profile(request,pk):
    user = User.objects.get(id=pk)
    return render(request ,'user_profile.html', context={'user':user})

@login_required
def view_chats(request):
    chats = Chat.objects.filter(participants=request.user)
    chat_entries = []
    
    for chat in chats:
        participant = chat.participants.exclude(id=request.user.id).first()
        
        chat_entries.append((chat, participant))
    
    return render(request, 'my_chats.html', context={'chat_entries': chat_entries})

@login_required
def chat(request, recipient_id):
    user = request.user
    recipient = get_object_or_404(User, id=recipient_id)
    
    chat = Chat.objects.filter(participants=user).filter(participants=recipient).first()
    
    if not chat:
        chat = Chat.objects.create(title=f"Chat between {user.username} and {recipient.username}")
        chat.participants.add(user, recipient)
        
    if request.method == 'POST':
        content = request.POST.get('content')
        Message.objects.create(sender=request.user, recipient=recipient, content=content, chat=chat)

    return render(request, 'chat.html', {'chat': chat})

@login_required
def my_listings(request):
    user = request.user
    listings = user.car_set.all()
    return render(request, 'my_listings.html', context={'user':user, 'listings':listings})

base/templates/car.html
{% extends "index.html" %}
{% load static %}
{% block content %}

<div class='car_top'>
    <a href="{{request.META.HTTP_REFERER}}">&#60; Go back</a>
    {% if request.user == car.user %}
    <a class='btn' href={% url "edit_car" car.id %}>Edit</a>
    {% endif %}
  </div>
  
  {% if car.images.all.count != 0 %}
  <div class='container4'>
    <div class='car_left'>
        {% for image in car.images.all %}
            <img src="{{ image.image.url }}" alt="{{ car.brand }} {{ car.model }} Image" class="{% if forloop.first %}active{% endif %}">
        {% endfor %}
        <button class="prev" onclick="changeSlide(-1)">&#8249; </button>
        <button class="next" onclick="changeSlide(1)"> &#8250;</button>
    </div>
    {% else %}
    <div class='container4'>
        <div class='car_left2'>
            <img src={% static "images/default_car.jpg" %}>
        </div>
    {% endif %}

    <div class='car_right'>
        <div class='one'>
            <h1>{{ car.brand }} {{ car.model }}</h1>
        </div>

        <div class='two'>
            <img src='{% static "images/date.png" %}'>
            <p>{{ car.first_registration_year }}</p>

            <img src='{% static "images/road.png" %}'>
            <p>{{ car.mileage }} km</p>

            <img src='{% static "images/petrol.png" %}'>
            <p>{{ car.fuel_type }}</p>
        </div>

        <div class='three'>
            <p><strong>Price:</strong> {{ car.price }} $</p>
        </div>

        <div class='car_user'>
            <div class='one'>
                <a href={% url "user_profile" pk=car.user.id %}><p><strong>Seller:</strong> {{ car.user.username }}</p></a>
                <p><strong>Contact Number:</strong> {{ car.user.profile.contact_number }}</p>
                <p><strong>Localization:</strong> {{ car.country }} {{ car.city }}</p>
            </div>
            {% if user.is_authenticated %}
            <a href="{% url 'chat' recipient_id=car.user.id %}"><button>Go to Chat</button></a>
            {% else %}
            <a href="{% url 'login' %}"><button>Go to Chat</button></a>
            {% endif %}
            <a href="tel:{{ car.user.profile.contact_number }}"><button>Call Seller</button></a>
        </div>
    </div>
</div>

<div class='container5'>
    <strong>Car Details:</strong>
    <div class='container6'>
        <div class='left1'>
            <p><strong>Car Brand:</strong> {{ car.brand }}</p>
            <p><strong>Car Model:</strong> {{ car.model }}</p>
            <p><strong>Registration Year:</strong> {{ car.first_registration_year }}</p>
            <p><strong>Mileage:</strong> {{ car.mileage }}</p>
        </div>
        <div class='mid1'>
            <p><strong>Fuel Type:</strong> {{ car.fuel_type }}</p>
            <p><strong>Horse Power:</strong> {{ car.horse_power }}</p>
            <p><strong>Transmission:</strong> {{ car.transmission }}</p>
            <p><strong>Body:</strong> {{ car.body }}</p>
        </div>
        <div class='right1'>
            <h1>Description:</h1>
            <div id="descriptionContainer">
                <p id="shortDescription">{{ car.description|truncatewords:50 }}</p>
                <p id="fullDescription" style="display: none;">{{ car.description }}</p>
            </div>
            <button onclick="toggleDescription()" id="showMoreButton">Show more</button>
        </div>
    </div>
</div>


{% endblock content %}

base/templates/chat.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<div class='container7'>
    <div class='chat_top'>
        <a href="{{request.META.HTTP_REFERER}}">&#60; Go back</a>
    </div>

    <h1>{{chat.title}}</h1>

    <div class='chat' id="chat-messages">
        {% for message in chat.message_set.all %}
            <div class="messages">
                {% if message.sender.username == request.user.username %}
                <div class='send_messages'>
                    <p><strong>You:</strong> {{ message.content }}</p>
                    <small>{{ message.timestamp|date:"F j, Y H:i:s" }}</small>
                </div>
                {% else %}
                <div class='received_messages'>
                    <p><strong>{{ message.sender.username }}:</strong> {{ message.content }}</p>
                    <small>{{ message.timestamp|date:"F j, Y H:i:s" }}</small>
                </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    
        <form method="post">
                <div class='replay'>
                {% csrf_token %}
                <textarea placeholder='Type a message..' name="content" required></textarea>
                <button type="submit">Send Message</button>
            </div>
        </form>

</div>
    {% endblock content %}

base/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static 'style.css' %}>
    <script src={% static "js/scriptt.js" %}></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> 
    <title>Car List</title>
</head>
<body>
    <div class='nav-bar'>
        <div class='left'>
            <a href={% url "index" %}><h1 class='logo1'>AUTO<h1></a>
            <h1 class='logo2'><a href={% url "index" %}>CAR</a><h1>
        </div>
        {% if page == 'index' %}
            {% if messages %}
            {% for message in messages %}
            <p class='message'>{{message}}</p>
            {% endfor %}
            {% endif %}
            {% else %}
        {% endif %}
        <div class='right'>
            {% if user.is_authenticated %}
            <a href={% url "my_profile" %}><p>My Account<p></a>
            <p>|<p>
            <a href={% url "my_listings" %}><p>My Listings<p></a>
            <p>|<p>
            <a href={% url "my_chats" %}><p>My Chats<p></a>
            <p>|<p>
            <a href={% url "logout" %}><p>Log Out<p></a>
            <a href={% url "new_order" %}><button type='submit'>Start selling &#10003;</button></a>
            {% else %}
            <a href={% url "login" %}><p>Login<p></a>
            <p>|<p>
            <a href={% url "register" %}><p>Register<p></a>
            <a href={% url "login" %}><button type='submit'>Start selling &#10003;</button></a>
            {% endif %}
        </div>
    </div>
    {% block content %}
    <div class='container'>
        <form method='GET'>
            <div class='container1'>
                <div class='filter'>
                    {{filter.form.brand.label}}
                    {{ filter.form.brand }}
                </div>
                <div class='filter'>
                    {{ filter.form.model.label }}
                    {{ filter.form.model }}
                </div>
                <div class='filter'>
                    {{ filter.form.body.label }}
                    {{ filter.form.body }}
                </div>
                <div class='filter'>
                    {{ filter.form.first_registration_year.label }}
                    {{ filter.form.first_registration_year }}
                </div>
                <div class='filter'>
                    {{ filter.form.fuel_type.label }}
                    {{ filter.form.fuel_type }}
                </div>
                <div class='filter'>
                    {{ filter.form.max_price.label }}
                    {{ filter.form.max_price }}
                </div>
                <button type='submit'>Search</button>
            </div>
        </form>
    </div>
    <div class='main'>
        <div class='top'>
            <h1>Cars:</h1>
            <strong>Cars count: <p>{{ cars.count }}</p></strong>
        </div>
        
        <div class='sort'>
            <a href="?order_by=1{% if filter.data.brand %}&brand={{ filter.data.brand }}{% endif %}&model={{ filter.data.model }}&body={{ filter.data.body }}&first_registration_year={{ filter.data.first_registration_year }}&fuel_type={{ filter.data.fuel_type }}&max_price={{ filter.data.max_price }}">Lowest price</a>
            <a href="?order_by=2{% if filter.data.brand %}&brand={{ filter.data.brand }}{% endif %}&model={{ filter.data.model }}&body={{ filter.data.body }}&first_registration_year={{ filter.data.first_registration_year }}&fuel_type={{ filter.data.fuel_type }}&max_price={{ filter.data.max_price }}">Highest price</a>
            <a href="?order_by=3{% if filter.data.brand %}&brand={{ filter.data.brand }}{% endif %}&model={{ filter.data.model }}&body={{ filter.data.body }}&first_registration_year={{ filter.data.first_registration_year }}&fuel_type={{ filter.data.fuel_type }}&max_price={{ filter.data.max_price }}">Lowest Power</a>
            <a href="?order_by=4{% if filter.data.brand %}&brand={{ filter.data.brand }}{% endif %}&model={{ filter.data.model }}&body={{ filter.data.body }}&first_registration_year={{ filter.data.first_registration_year }}&fuel_type={{ filter.data.fuel_type }}&max_price={{ filter.data.max_price }}">Highest Power</a>
            <a href="?order_by=5{% if filter.data.brand %}&brand={{ filter.data.brand }}{% endif %}&model={{ filter.data.model }}&body={{ filter.data.body }}&first_registration_year={{ filter.data.first_registration_year }}&fuel_type={{ filter.data.fuel_type }}&max_price={{ filter.data.max_price }}">Oldest year</a>
            <a href="?order_by=6{% if filter.data.brand %}&brand={{ filter.data.brand }}{% endif %}&model={{ filter.data.model }}&body={{ filter.data.body }}&first_registration_year={{ filter.data.first_registration_year }}&fuel_type={{ filter.data.fuel_type }}&max_price={{ filter.data.max_price }}">Newest year</a>
        </div>

        {% for car in cars %}
        <a class='acar' href={% url "car" car.id %}>
        <div class='car'>
            <div class='left'>
                {% if car.images.all.count == 0 %}
                    <img src={% static "images/default_car.jpg" %}>
                {% endif %}
                {% for image in car.images.all %}
                {% if forloop.counter == 1 %}
                    <img src="{{ image.image.url }}">
                {% endif %}
                {% endfor %}
                <div class='imgcount'>
                    <p><img src={% static "images/camera.png" %}>{{car.images.count}}/10</p>
                </div>
            </div>
            <div class='mid'>
                <strong class='strong'>{{ car.brand }} {{ car.model }}</strong>
                <p></p>
                <p class='p1'><img src='{% static "images/horses.png" %}'><strong class='strong3'>Horse Power:</strong> {{ car.horse_power }} KM</p>
                <p class='p1'><img src='{% static "images/petrol.png" %}'><strong class='strong3'>Fuel:</strong> {{ car.fuel_type }}</p>
                <p class='p1'><img src='{% static "images/gear.png" %}'><strong class='strong3'>Transmission:</strong> {{ car.transmission }}</p>
                <p class='p1'><img src='{% static "images/date.png" %}'><strong class='strong3'>First registration year: </strong> {{ car.first_registration_year }}</p>
            </div>
            <div class='right'>
                <strong>{{ car.price }} $</strong>
                <strong class='strong2'>Localization:</strong>
                <p>{{ car.country }} ({{ car.city }})</p>
            </div>
        </div>
        </a>
        {% endfor %}

        <div class='end_bar'>
            <p>We are the largest automotive platform in Poland !</p>
            <p class='p'>Over 1 000 000 users a day !</p>
            <p>Over 200 000 active offerts !</p>
        </div>

    </div>
    {% endblock content %}
</body>
</html>

base/templates/login.html
{% extends "index.html" %}
{% block content %}
<div class='container'>
    <div class='login'>
        <h1><a href={% url "login" %}>Login</a> | <a href={% url "register" %}>Register</a></h1>
    </div>
    <div class='login'>
        <p class='pp3'>Login or Register and list cars for free!</p>
    </div>
</div>

<form method='POST'>
    {% csrf_token %}
    <div class='login_form'>
        {% if messages %}
        {% for message in messages %}
        <p class='error'>{{message}}</p>
        {% endfor %}
        {% endif %}
        <p>Username</p>
        <input name='username' type='text' placeholder='Username'>
        <p>Password</p>
        <input name='password' type="password" id="myInput" placeholder='Password'>
        <div class='password'>
            <p>Show Password</p>
            <input type="checkbox" onclick="showPassword()">
        </div>
        <button type='submit'>Submit</button>
        <a class='a' href={% url "register" %}><p>Dont have an account? Register now!</p></a>
    <div>
</form>
<div class='end_bar2'>
    <p>We are the largest automotive platform in Poland !</p>
    <p class='p'>Over 1 000 000 users a day !</p>
    <p>Over 200 000 active offerts !</p>
</div>
{% endblock content %}


base/templates/my_chats.html
{% extends "index.html" %}
{% block content %}
<div class='container'>
    <h1 class='title'>My Chats</h1>
</div>
{% if chat_entries %}
{% for chat, recipient in chat_entries %}
    <div class='my_chats'>
        <p>Chat between You and {{recipient.username}}</p>
        <button><a href="{% url 'chat' recipient_id=recipient.id %}">View</a></button>
    </div>
{% endfor %}
{% else %}
<div>
    <p>You dont have any chats yet! </p>
</div>
{% endif %}
{% endblock content %}

base/templates/my_listings.html
{% extends "index.html" %}
{% block content %}
<div class='container'>
    <h1 class='title'>My Listings</h1>
</div>
<div class='container8'>
    {% for car in listings %}
        <a href={% url "car" pk=car.id %}>{{car.brand}} {{car.model}}</a>
    {% endfor %}
</div>
{% endblock content %}

base/templates/my_profile.html
{% extends "index.html" %}
{% block content %}
<div class='container'>
    <h1 class='title'>My Profile</h1>
</div>
<div class='profile'>
    {% if messages %}
    {% for message in messages %}
    <p class='succes'>{{message}}</p>
    {% endfor %}
    {% endif %}
    <p>{{user.username}}</p>
    <form method='POST'>
        <div class='disc'>
        {% csrf_token %}
        {% for field in form %}
        <p>{{field.label}}:</p>
        {{field}}
        {% endfor %}
        <button type='submit'>Edit</button>
        </div>
    </form>
</div>
{% endblock content %}
